////////////////////////////////////////////////////////////////////////////////
//
//    Copyright (c) 2022 - 2024.
//    Haixing Hu, Qubit Co. Ltd.
//
//    All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
package ltd.qubit.model;

import java.util.Locale;

import ltd.qubit.commons.lang.EnumUtils;

import static ltd.qubit.commons.lang.EnumUtils.registerLocalizedNames;

/**
 * 此枚举表示实体的属性。
 *
 * @author 胡海星
 */
public enum Field {
  ACTION,
  ACTUAL,
  ACTUAL_CREDENTIAL_NUMBER,
  ACTUAL_CREDENTIAL_TYPE,
  ADDRESS_DETAIL,
  ADDRESS_LATITUDE,
  ADDRESS_LONGITUDE,
  ADDRESS_POSTALCODE,
  ADDRESS_STREET_ID,
  ADDRESS_VERIFY,
  AGE,
  ALTITUDE,
  APP,
  APP_ID,
  AVATAR,
  BIRTHDAY,
  BLOOD,
  BUYER,
  BUYER_ID,
  CATEGORY_ID,
  CHANGE_PASSWORD,
  CHANNEL,
  CHANNEL_NUMBER,
  CITY,
  CITY_ID,
  CLIENT,
  CODE,
  COMMENT,
  COMPLETE_TIME,
  COST,
  COUNT,
  COUNTRY,
  COUNTRY_ID,
  CREATE_TIME,
  CREATOR_ID,
  CREDENTIAL,
  CREDENTIAL_NUMBER,
  CREDENTIAL_TYPE,
  CREDENTIAL_VERIFY,
  CURRENCY,
  DELETER_ID,
  DELETE_TIME,
  DESCRIPTION,
  DICT,
  DISCOUNT,
  DISCOUNT_REASON,
  DISTRICT,
  DISTRICT_ID,
  EDUCATION,
  EMAIL,
  EMAIL_VERIFY,
  ENCRYPTED,
  ENTITY,
  ERROR_CODE,
  ERROR_MESSAGE,
  ERROR_PARAMS,
  ERROR_TYPE,
  ETHNIC,
  EXPECTED,
  EXPECTED_CREDENTIAL_NUMBER,
  EXPECTED_CREDENTIAL_TYPE,
  EXPIRED_REASON,
  EXPIRED_TIME,
  FULLNAME,
  GENDER,
  GUARDIAN,
  HAS_CHILD,
  HAS_MEDICARE,
  HAS_MEDICARE_OR_SOCIAL_SECURITY,
  HAS_SOCIAL_SECURITY,
  HEIGHT,
  HOST,
  ICON,
  ID,
  IMAGE,
  INCOMING,
  INDUSTRY,
  INVENTORY,
  INVOICE_STATUS,
  IP,
  ITEM_ID,
  JOB,
  JOB_TITLE,
  LAST_ACTIVE_TIME,
  LAST_LOGIN_FAILURES,
  LAST_LOGIN_TIME,
  LATITUDE,
  LEVEL,
  LOGIN_TIME,
  LONGITUDE,
  MANUFACTURER_ID,
  MARRIAGE,
  MEDICARE_CITY,
  MEDICARE_CITY_ID,
  MOBILE,
  MOBILE_CITY_AREA,
  MOBILE_COUNTRY_AREA,
  MOBILE_NUMBER,
  MOBILE_VERIFY,
  MODE,
  MODIFIER_ID,
  MODIFY_TIME,
  MULTIPLE,
  NAME,
  NEED_DELIVERY,
  NEW_CREDENTIAL_NUMBER,
  NEW_CREDENTIAL_TYPE,
  NEW_EMAIL,
  NEW_FULLNAME,
  NEW_MOBILE,
  NICKNAME,
  NULLABLE,
  NUMBER,
  OLD_CREDENTIAL_NUMBER,
  OLD_CREDENTIAL_TYPE,
  OLD_EMAIL,
  OLD_FULLNAME,
  OLD_MOBILE,
  OPERATION,
  OPERATOR_ID,
  ORDER_ID,
  ORDER_ITEM,
  ORDER_ITEM_ID,
  ORDER_TITLE,
  ORGANIZATION,
  ORGANIZATION_ID,
  ORGANIZATION_NAME,
  ORIGIN_ID,
  OWNER,
  OWNER_CODE,
  OWNER_ID,
  OWNER_TYPE,
  PAID,
  PARENT_ID,
  PASSWORD,
  PAYABLE,
  PAYEE_ACCOUNT_ID,
  PAYEE_ALTITUDE,
  PAYEE_CREDENTIAL_NUMBER,
  PAYEE_CREDENTIAL_TYPE,
  PAYEE_EMAIL,
  PAYEE_ID,
  PAYEE_IP,
  PAYEE_LATITUDE,
  PAYEE_LONGITUDE,
  PAYEE_NAME,
  PAYEE_PHONE,
  PAYEE_PLATFORM,
  PAYEE_TYPE,
  PAYER_ACCOUNT_ID,
  PAYER_ALTITUDE,
  PAYER_CREDENTIAL_NUMBER,
  PAYER_CREDENTIAL_TYPE,
  PAYER_EMAIL,
  PAYER_ID,
  PAYER_IP,
  PAYER_LATITUDE,
  PAYER_LONGITUDE,
  PAYER_NAME,
  PAYER_PHONE,
  PAYER_PLATFORM,
  PAYER_TYPE,
  PAY_TIME,
  PERSON_ID,
  PHONE,
  PHONE_AREA,
  PHONE_CITY_AREA,
  PHONE_COUNTRY_AREA,
  PHONE_NUMBER,
  PHONE_VERIFY,
  PLATFORM,
  POSTALCODE,
  PREDEFINED,
  PRESCRIPTION_ID,
  PRICE,
  PRIVATE_KEY,
  PRIVILEGES,
  PRODUCT,
  PRODUCTION_DATE,
  PRODUCT_CODE,
  PRODUCT_COUNT,
  PRODUCT_CURRENCY,
  PRODUCT_DESCRIPTION,
  PRODUCT_ID,
  PRODUCT_IMAGE,
  PRODUCT_ITEM,
  PRODUCT_ITEM_ID,
  PRODUCT_NAME,
  PRODUCT_PRICE,
  PRODUCT_QUALITY,
  PRODUCT_SPECIFICATION,
  PRODUCT_UNIT,
  PROVIDER_APP,
  PROVIDER_APP_ID,
  PROVINCE,
  PROVINCE_ID,
  PUSH_TOKEN,
  READ_ONLY,
  REFUND_TIME,
  RELIGION,
  ROLE,
  RSA_PUBLIC_KEY,
  SALE_END_DATE,
  SALE_START_DATE,
  SCENE,
  SECURITY_KEY,
  SELLER,
  SELLER_ID,
  SEX_ORIENTATION,
  SHIPPING_COST,
  SHIPPING_DEMAND,
  SHIPPING_MODE,
  SHIPPING_NUMBER,
  SHIP_TIME,
  SOCIAL_SECURITY_CITY,
  SOCIAL_SECURITY_CITY_ID,
  SOURCE,
  SOURCE_ID,
  SPECIFICATION,
  STATE,
  STATUS,
  SUCCESS,
  TARGET_ID,
  TARGET_TYPE,
  TIMESTAMP,
  TITLE,
  TOKEN,
  TOKEN_CREATE_TIME,
  TOKEN_EXPIRED_TIME,
  TOTAL_DISCOUNT,
  TOTAL_PRICE,
  TRANSACTION_ID,
  TYPE,
  UDID,
  UNIT,
  UPLOAD_ID,
  URL,
  USER,
  USERNAME,
  USER_ID,
  VALID_TIME,
  VALUE,
  VERIFY,
  VERIFY_CODE,
  WEIGHT,
  OPENID_TYPE,

  OPENID,

  QUESTION,

  THIRDPARTY_INSURANCE_ID,

  ACCIDENT_REASON,

  POLICY_NUMBER,

  KINSHIP_TYPE,

  CLAIMANT,

  ACCIDENT_DATE,

  ACCIDENT_PLACE,

  ACCIDENT_DESCRIPTION,

  ACCOUNT,

  ACCOUNT_TYPE,

  INSURED,

  CLAIM_ID,

  CLAIM_MEDICAL_ID,

  CLAIM_INVOICE_ID,

  INVOICE_NUMBER,

  TREATMENT_DATE,

  AMOUNT,

  INVOICE_LIST,

  FUND_PAID_AMOUNT,

  SELF_PAID_AMOUNT,

  SELF_CARE_AMOUNT,

  MEDICARE_AMOUNT,

  SERIOUS_ILLNESS_PAID,

  SERIOUS_ILLNESS_INSURANCE_PAID,

  CIVIL_AFFAIR_SUBSIDY_PAID,

  MESSAGE_KEY,

  PRIMARY_DIAGNOSIS,

  MEDICAL_CHARGE_NAME;

  static {
    registerLocalizedNames(Entity.class, "i18n/common-model/field");
  }

  public String code() {
    return name().toLowerCase();
  }

  public String getLocalizedName() {
    return getLocalizedName(Locale.getDefault());
  }

  public String getLocalizedName(final Locale locale) {
    return EnumUtils.getLocalizedName(locale, this);
  }

}
